import { makeStyles } from '@material-ui/core';

export const useStyles = makeStyles({
  downloadBtn: {
    width: '100%',
    height: '50px',
    backgroundColor: '#1e90ff',
    borderRadius: '3px',
    border: '0px',
    color: '#fff !important',
    fontSize: '20px',
    fontWeight: '700',
  },
  commRating: {
    fontSize: '20px',
  },
  userInfoInput: {
    minWidth: '400px',
    fontSize: '20px',
    marginLeft: 60,
    borderRadius: 5,
    border: '2px solid rgb(205,205,205)',
    padding: '5px 20px',
    transition: '0.1s linear',
    '&:focused': {
      boxShadow: '5px 5px 5px 1px rgba(40, 40, 40, 0.3)',
      borderColor: '#4169e1',
    },
  },
  userInfoUpdateBtn: {
    width: '200px',
    fontSize: '16px',
    margin: 30,
    borderRadius: 3,
    border: '2px solid #0000cd',
    backgroundColor: '#4169e1',
    color: 'white',
    padding: '7px 0',
  },
  userInfoCancelBtn: {
    width: '200px',
    fontSize: '16px',
    margin: 30,
    borderRadius: 3,
    border: '2px solid #222222',
    backgroundColor: '#505050',
    color: 'white',
    padding: '7px 0',
  },
  uploadBtn: {
    width: `150px`,
    borderRadius: '3px',
    border: '2px solid #4169e1',
    backgroundColor: '#4169e1',
    color: 'white',
    padding: '10px 0',
  },
  checkedListUpdateBtn: {
    width: `80px`,
    height: '30px',
    borderRadius: '3px',
    border: '2px solid #808080',
    backgroundColor: '#808080',
    color: 'white',
    padding: '5px 0',
  },
  fileSelctionBtn: {
    width: `100px`,
    borderRadius: '3px',
    border: '2px solid #808080',
    backgroundColor: '#808080',
    color: 'white',
    padding: '10px 0',
  },
  uploadSelectForm: {
    minWidth: 150,
    marginRight: 16,
  },
  uploadSelect: {
    fontSize: '16px',
    borderRadius: 5,
    border: '2px solid rgb(205,205,205)',
    padding: '6px 12px',
  },
  chkboxGr: {
    minWidth: 100,
  },
  emailChkBtn: {
    minWidth: '64px',
    color: 'white',
    background: 'darkgray',
  },
  joinFormBtn: {
    height: '40px',
    fontWeight: '500',
    fontSize: '20px',
    color: '#fff !important',
    border: '0px',
    borderRadius: '3px',
    width: '423px',
    background: '#1e90ff',
  },
});
