spring:
  # mysql connection
  datasource:
    url: jdbc:mysql://localhost:3306/blockfish
    password: 96117vb@
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        show_sql: true
        format_sql: true
  cache:
    type: redis
  redis:
    host: 127.0.0.1  #원격서버 배포시 원격 서버 아이피로 변경 후, 방화벽 열어주기(ec2 사용시 보안그룹에서 포트 열어주기), redis-cli에서 접속 여부 확인 후 배포
    port: 6379

  mail:
    host: smtp.gmail.com
    username: blockfish3
    password: 123abc123!
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB


  # JWT Secret key
  jwt:
    secret: kimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeun

logging:
  level:
    root: INFO
    com.project.blockfish: DEBUG
  file:
    path: logs