spring:
  # mysql connection
  datasource:
    url: jdbc:mysql://localhost:3306/blockfish
    password: alsgh3144
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379

  mail:
    host: smtp.gmail.com
    username: blockfish3
    password: 123abc123!
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB


  # JWT Secret key
  jwt:
    secret: kimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeun