spring:
  # mysql connection
  datasource:
    url: jdbc:mysql://localhost:3306/blockfish
    password: alsgh3144
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379

  # JWT Secret key
  jwt:
    secret: kimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeunkimdonggeun